/*7. Write a c program that input values for m and n and display the values of the Pythagorean triple generated by following formulas.
Side1=m^2  -  n^2
Side2=2mn
Hypotenuse=m^2+n^2
*/
#include <stdio.h>
int main(int argc, char const *argv[]) {
  int m,n,side_1,side_2,hypotenuse;
  printf("Enter The Value Of m:");
  scanf("%d",&m);
  printf("Enter The Value Of n:");
  scanf("%d", &n);
  side_1= (m*m)-(n*n);
  side_2 = 2*m*n;
  hypotenuse =(m*m)+(n*n);
  printf("Side_1 = %d\n",side_1);
  printf("Side_2 = %d\n",side_2);
  printf("Hypotenuse = %d\n",hypotenuse);
  return 0;
}
